Repository xbmc/xbmc, pull requests merged in 2025-07, with the labels that each got.

#26830 [CURL][tests] Fixed encoding of rar files to be consistent with zip etc...
  xbmc/utils/URIUtils.cpp
  xbmc/utils/test/TestURIUtils.cpp
Labels: Type: Fix, v22 Piers

#26935 [Video] Fix scraper cache needs content type to be part of key otherwise content type is not updated if two sources using the same scraper with different content are scanned.
  xbmc/video/VideoDatabase.cpp
Labels: Type: Fix, v22 Piers

#26938 [Video] Fix GetMovieName(), GetMovieBasePath() and GetBasePath() to better handle optical media, bluray:// paths and Disc n subdirectories. Add tests.
  xbmc/FileItem.cpp
  xbmc/Util.cpp
  xbmc/Util.h
  xbmc/filesystem/BlurayDirectory.cpp
  xbmc/test/TestFileItem.cpp
  xbmc/test/TestUtil.cpp
  xbmc/utils/URIUtils.cpp
  xbmc/utils/URIUtils.h
  xbmc/utils/test/TestURIUtils.cpp
  xbmc/video/VideoDatabase.cpp
  xbmc/video/VideoInfoScanner.cpp
Labels: Type: Fix, Component: Video, v22 Piers

#26936 [Video][Bluray] Fix duplicate movie/episode entry created after library update if a bluray movie/episode has been played and folder rescanned (eg. adding file, post-import etc.)
  xbmc/video/VideoDatabase.cpp
Labels: Type: Fix, Component: Video, v22 Piers

#26924 [Game API] Fix grammar and improve docs
  xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/Game.h
  xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/game.h
Labels: Type: Improvement, Component: Games, v22 Piers

#26948 [Bluray] Fix failure to compile on linux without libbluray.
  xbmc/utils/URIUtils.cpp
Labels: Type: Fix, Component: Video, v22 Piers

#26928 [Android] Enable displaying recommended content on Projectivy Launcher
  tools/android/packaging/xbmc/src/Main.java.in
Labels: Type: Improvement, Platform: Android, v22 Piers

#26955 [Bluray] fix build ENABLE_BLURAY=NO && ENABLE_OPTICAL=YES
  xbmc/storage/MediaManager.cpp
Labels: Type: Fix, v22 Piers

#26954 [Bluray] Further linux bluray complie fix (Fix #26953).
  xbmc/utils/URIUtils.cpp
Labels: Type: Fix, v22 Piers

#26951 RetroPlayer: Add integer scaling support
  addons/resource.language.en_gb/resources/strings.po
  xbmc/cores/GameSettings.h
  xbmc/cores/RetroPlayer/RetroPlayerUtils.cpp
  xbmc/cores/RetroPlayer/rendering/RenderUtils.cpp
  xbmc/cores/RetroPlayer/rendering/RenderUtils.h
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPBaseRenderer.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderPreset.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderPreset.h
  xbmc/games/dialogs/osd/DialogGameStretchMode.cpp
Labels: Type: Feature, Component: Games, v22 Piers

#26295 [Video] Add refresh set functionality, set.nfo support and improve add/update set consistency with Movie Set Information Folder.
  xbmc/guilib/guiinfo/VideoGUIInfo.cpp
  xbmc/interfaces/legacy/InfoTagVideo.cpp
  xbmc/utils/GroupUtils.cpp
  xbmc/video/CMakeLists.txt
  xbmc/video/SetInfoTag.cpp
  xbmc/video/SetInfoTag.h
  xbmc/video/VideoDatabase.cpp
  xbmc/video/VideoDatabase.h
  xbmc/video/VideoInfoScanner.cpp
  xbmc/video/VideoInfoScanner.h
  xbmc/video/VideoInfoTag.cpp
  xbmc/video/VideoInfoTag.h
  xbmc/video/VideoThumbLoader.cpp
  xbmc/video/dialogs/GUIDialogVideoInfo.cpp
  xbmc/video/jobs/VideoLibraryRefreshingJob.cpp
  xbmc/video/tags/CMakeLists.txt
  xbmc/video/tags/ISetInfoTagLoader.h
  xbmc/video/tags/SetInfoTagLoaderFactory.cpp
  xbmc/video/tags/SetInfoTagLoaderFactory.h
  xbmc/video/tags/SetTagLoaderNFO.cpp
  xbmc/video/tags/SetTagLoaderNFO.h
  xbmc/video/windows/GUIWindowVideoBase.cpp
Labels: Type: Improvement, Component: Video, v22 Piers

#26974 [utils] SonarQube finding: CEventStream, CSubscription: Replace function pointers with std::function
  xbmc/ContextMenuManager.cpp
  xbmc/addons/BinaryAddonCache.cpp
  xbmc/addons/BinaryAddonCache.h
  xbmc/addons/ExtsMimeSupportList.cpp
  xbmc/addons/ExtsMimeSupportList.h
  xbmc/addons/RepositoryUpdater.cpp
  xbmc/addons/RepositoryUpdater.h
  xbmc/addons/Service.cpp
  xbmc/addons/VFSEntry.cpp
  xbmc/addons/VFSEntry.h
  xbmc/addons/gui/GUIWindowAddonBrowser.cpp
  xbmc/addons/gui/GUIWindowAddonBrowser.h
  xbmc/cores/RetroPlayer/shaders/ShaderPresetFactory.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderPresetFactory.h
  xbmc/favourites/FavouritesUtils.cpp
  xbmc/favourites/GUIWindowFavourites.cpp
  xbmc/favourites/GUIWindowFavourites.h
  xbmc/games/agents/windows/GUIAgentControllerList.cpp
  xbmc/games/agents/windows/GUIAgentControllerList.h
  xbmc/games/controllers/ControllerManager.cpp
  xbmc/games/controllers/ControllerManager.h
  xbmc/games/controllers/windows/GUIControllerList.cpp
  xbmc/games/controllers/windows/GUIControllerList.h
  xbmc/games/controllers/windows/GUIControllerWindow.cpp
  xbmc/games/controllers/windows/GUIControllerWindow.h
  xbmc/games/ports/guicontrols/GUIActivePortList.cpp
  xbmc/games/ports/guicontrols/GUIActivePortList.h
  xbmc/games/ports/windows/GUIPortList.cpp
  xbmc/games/ports/windows/GUIPortList.h
  xbmc/guilib/listproviders/DirectoryProvider.cpp
  xbmc/peripherals/bus/virtual/PeripheralBusAddon.cpp
  xbmc/peripherals/bus/virtual/PeripheralBusAddon.h
  xbmc/pvr/addons/PVRClients.cpp
  xbmc/pvr/addons/PVRClients.h
  xbmc/pvr/channels/PVRChannel.cpp
  xbmc/pvr/channels/PVRChannel.h
  xbmc/pvr/channels/PVRChannelGroups.cpp
  xbmc/pvr/channels/PVRChannelGroups.h
  xbmc/pvr/dialogs/GUIDialogPVRChannelsOSD.cpp
  xbmc/pvr/dialogs/GUIDialogPVRChannelsOSD.h
  xbmc/pvr/epg/EpgContainer.cpp
  xbmc/pvr/guilib/PVRGUIActionListener.cpp
  xbmc/pvr/guilib/PVRGUIActionListener.h
  xbmc/pvr/guilib/PVRGUIActionsChannels.cpp
  xbmc/pvr/guilib/PVRGUIActionsChannels.h
  xbmc/pvr/guilib/PVRGUIChannelNavigator.cpp
  xbmc/pvr/guilib/PVRGUIChannelNavigator.h
  xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp
  xbmc/pvr/guilib/guiinfo/PVRGUIInfo.h
  xbmc/pvr/timers/PVRTimers.cpp
  xbmc/pvr/timers/PVRTimers.h
  xbmc/pvr/windows/GUIWindowPVRBase.cpp
  xbmc/pvr/windows/GUIWindowPVRBase.h
  xbmc/utils/EventStream.h
  xbmc/utils/EventStreamDetail.h
  xbmc/utils/FileExtensionProvider.cpp
  xbmc/utils/FileExtensionProvider.h
Labels: Type: Cleanup, v22 Piers

#26975 [video] SonarQube finding: Make CVideoActionProcessorBase members m_item and m_userCancelled private.
  xbmc/pvr/dialogs/GUIDialogPVRGuideInfo.cpp
  xbmc/pvr/dialogs/GUIDialogPVRRecordingInfo.cpp
  xbmc/video/dialogs/GUIDialogVideoInfo.cpp
  xbmc/video/guilib/VideoActionProcessorBase.h
  xbmc/video/guilib/VideoPlayActionProcessor.cpp
  xbmc/video/guilib/VideoPlayActionProcessor.h
  xbmc/video/guilib/VideoSelectActionProcessor.cpp
  xbmc/video/windows/GUIWindowVideoBase.cpp
  xbmc/video/windows/GUIWindowVideoPlaylist.cpp
Labels: Type: Cleanup, Component: Video, v22 Piers

#26964 Fixed use-after-free of Wayland Connection on webOS
  xbmc/windowing/wayland/WinSystemWayland.cpp
  xbmc/windowing/wayland/WinSystemWaylandWebOS.cpp
  xbmc/windowing/wayland/WinSystemWaylandWebOS.h
Labels: Component: Windowing, Platform: webOS, v22 Piers

#26985 [cores/Retroplayer/shaders] Misc SonarQube findings, episode 2
  xbmc/cores/RetroPlayer/shaders/IShader.h
  xbmc/cores/RetroPlayer/shaders/IShaderLut.h
  xbmc/cores/RetroPlayer/shaders/IShaderPreset.h
  xbmc/cores/RetroPlayer/shaders/IShaderPresetLoader.h
  xbmc/cores/RetroPlayer/shaders/IShaderSampler.h
  xbmc/cores/RetroPlayer/shaders/IShaderTexture.cpp
  xbmc/cores/RetroPlayer/shaders/IShaderTexture.h
  xbmc/cores/RetroPlayer/shaders/ShaderPreset.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderPreset.h
  xbmc/cores/RetroPlayer/shaders/ShaderPresetFactory.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderPresetFactory.h
  xbmc/cores/RetroPlayer/shaders/ShaderTypes.h
  xbmc/cores/RetroPlayer/shaders/ShaderUtils.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderUtils.h
  xbmc/cores/RetroPlayer/shaders/gl/ShaderGL.cpp
  xbmc/cores/RetroPlayer/shaders/gl/ShaderGL.h
  xbmc/cores/RetroPlayer/shaders/gl/ShaderLutGL.cpp
  xbmc/cores/RetroPlayer/shaders/gl/ShaderLutGL.h
  xbmc/cores/RetroPlayer/shaders/gl/ShaderPresetGL.cpp
  xbmc/cores/RetroPlayer/shaders/gl/ShaderTextureGL.cpp
  xbmc/cores/RetroPlayer/shaders/gl/ShaderUtilsGL.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderGLES.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderGLES.h
  xbmc/cores/RetroPlayer/shaders/gles/ShaderLutGLES.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderLutGLES.h
  xbmc/cores/RetroPlayer/shaders/gles/ShaderPresetGLES.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderTextureGLES.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderTextureGLES.h
  xbmc/cores/RetroPlayer/shaders/gles/ShaderUtilsGLES.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderUtilsGLES.h
  xbmc/cores/RetroPlayer/shaders/windows/RPWinOutputShader.cpp
  xbmc/cores/RetroPlayer/shaders/windows/RPWinOutputShader.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderDX.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderLutDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderLutDX.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderPresetDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderSamplerDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderSamplerDX.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderTextureDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderTextureDX.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderTextureDXRef.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderTextureDXRef.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderTypesDX.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderUtilsDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderUtilsDX.h
Labels: Type: Cleanup, Component: Players, v22 Piers

#26983 [utils/log.*] Use a dedicated logger for every pre-defined logging component
  xbmc/utils/Map.h
  xbmc/utils/log.cpp
  xbmc/utils/log.h
Labels: Type: Improvement, v22 Piers

#26992 [tools/depends][native] Fix pkg-config build with gcc 15
  tools/depends/native/pkg-config/001-fix-gcc15-build.patch
  tools/depends/native/pkg-config/Makefile
Labels: Type: Fix, Component: Depends, v22 Piers

#26996 [ffmpeg] Use AV_PROFILE_* defines instead of the deprecated FF_PROFILE_*
  xbmc/cores/VideoPlayer/AudioSinkAE.cpp
  xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp
  xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp
  xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp
  xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.cpp
  xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h
  xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp
  xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
  xbmc/cores/paplayer/VideoPlayerCodec.cpp
  xbmc/utils/StreamUtils.cpp
Labels: Type: Cleanup, Type: Improvement, v22 Piers

#26704 [Backport] Fix Info Dialog for Versions of Same Name
  xbmc/FileItem.cpp
  xbmc/interfaces/json-rpc/PlayerOperations.cpp
  xbmc/interfaces/json-rpc/VideoLibrary.cpp
  xbmc/network/upnp/UPnPServer.cpp
  xbmc/video/VideoDatabase.cpp
  xbmc/video/VideoDatabase.h
  xbmc/video/dialogs/GUIDialogVideoInfo.cpp
  xbmc/video/windows/GUIWindowVideoBase.cpp
Labels: Type: Fix, Component: Video, Type: Backport, Component: Windowing, Component: JSON-RPC, v21 Omega, Feature: Video Versions/Extras

#26779 [Backport][Xbox] Fix HDR support for Xbox One models
  xbmc/rendering/dx/DeviceResources.cpp
Labels: Type: Fix, Platform: Windows, Type: Backport, Platform: WindowsStore, Component: DirectX rendering, v21 Omega

#26980 [VideoPlayer][Bluray] Fix #26943 - on bluray resume audio/subs (inc external subs) language is not restored.
  xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.cpp
  xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.h
  xbmc/cores/VideoPlayer/VideoPlayer.cpp
  xbmc/video/VideoDatabase.cpp
Labels: Type: Fix, Backport: Done, Component: Video, v22 Piers

#26961 RetroPlayer: Fix video shaders scaling
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPBaseRenderer.cpp
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPBaseRenderer.h
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererDMAOpenGL.cpp
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererDMAOpenGLES.cpp
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererOpenGL.cpp
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererOpenGLES.cpp
  xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPWinRenderer.cpp
  xbmc/cores/RetroPlayer/shaders/IShader.h
  xbmc/cores/RetroPlayer/shaders/IShaderPreset.h
  xbmc/cores/RetroPlayer/shaders/ShaderPreset.cpp
  xbmc/cores/RetroPlayer/shaders/ShaderPreset.h
  xbmc/cores/RetroPlayer/shaders/gl/ShaderGL.cpp
  xbmc/cores/RetroPlayer/shaders/gl/ShaderGL.h
  xbmc/cores/RetroPlayer/shaders/gl/ShaderPresetGL.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderGLES.cpp
  xbmc/cores/RetroPlayer/shaders/gles/ShaderGLES.h
  xbmc/cores/RetroPlayer/shaders/gles/ShaderPresetGLES.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderDX.cpp
  xbmc/cores/RetroPlayer/shaders/windows/ShaderDX.h
  xbmc/cores/RetroPlayer/shaders/windows/ShaderPresetDX.cpp
Labels: Type: Fix, Component: Games, v22 Piers

#27002 [fix] unused-private-field warning
  xbmc/games/agents/input/AgentMouse.h
Labels: Type: Fix, v22 Piers

#26848 [Omega][macOS] key handling improvements
  xbmc/windowing/osx/WinEventsOSXImpl.mm
Labels: Platform: macOS, Type: Backport, v21 Omega

#26274 [Video] Import/export improvements and fixes - including multi-episode file support (including blurays).
  xbmc/NfoFile.cpp
  xbmc/utils/ArtUtils.cpp
  xbmc/utils/ArtUtils.h
  xbmc/utils/test/TestArtUtils.cpp
  xbmc/video/VideoDatabase.cpp
  xbmc/video/VideoDatabase.h
  xbmc/video/VideoInfoScanner.cpp
  xbmc/video/VideoInfoTag.cpp
  xbmc/video/VideoInfoTag.h
  xbmc/video/tags/VideoTagLoaderNFO.cpp
Labels: Type: Fix, Type: Improvement, Wiki: Needed, Component: Video, v22 Piers

#27006 URIUtils: Include resource:// protocol in IsHD check
  xbmc/utils/URIUtils.cpp
Labels: Type: Fix, Component: GUI engine, v22 Piers

#27004 [clang-tidy] fix performance-* warnings
  xbmc/cores/RetroPlayer/shaders/ShaderPresetFactory.cpp
  xbmc/interfaces/legacy/ListItem.cpp
  xbmc/interfaces/legacy/ListItem.h
  xbmc/video/VideoInfoTag.cpp
  xbmc/video/VideoInfoTag.h
Labels: Type: Fix, v22 Piers

#27022 [splash] revert logic of message selection after #27012
  xbmc/application/Application.cpp
Labels: Type: Fix, v22 Piers

#27023 Revert "[depends] Update to libnfs 6.0.2"
  cmake/modules/FindNFS.cmake
  tools/depends/target/libnfs/01-MSUWP-compat.patch
  tools/depends/target/libnfs/LIBNFS-VERSION
  tools/depends/target/libnfs/Makefile
Labels: Type: Fix, Component: Depends, v22 Piers
